### ISSUE TITLE
adapt ops inputs for ATOVS specific variables

### ISSUE THREAD

**Issue by brettcandy** [MetOffice/opsinputs#102]
The varobs file for ATOVS follows ATMS with the following additions

* Scene dependent variable obs error (created from the obs function  MetOfficeAllSkyErrorModel)
* IRemissivity 

The latter variable is expected by Var but will not actually be used since the IR channels for ATOVS are now no longer used. So we will need to adapt the opsinputs code to read in a new variable from the obs space generated by a simple variable assignment filter

Here is the comparison between ATMS and ATOVS

![Screenshot 2022-05-24 160941](https://user-images.githubusercontent.com/67381785/170069847-309563b2-418e-4837-8908-0c2f3d22680a.png)

**Comment by ctgh** [comment]
@brettcandy Can I check that this issue has been resolved by the accompanying PR?

**Comment by brettcandy** [comment]
indeed

**Comment by ctgh** [comment]
Thanks!
