### ISSUE TITLE
CX namelist for global surface observations

### ISSUE THREAD

**Issue by ldhawknesssmith** [MetOffice/opsinputs#153]
Include CX namelist for global Surface observations. 

This differs from the OPS equivalent as some fields used in OPS are not for assimilation, but only for mergeback, therefore this namelist removes a number of items which are requested by default. Those fields not required for assimilation have not been made available in the ops-um-interface.

**Comment by ctgh** [comment]
Closing this as complete. See #155 for further discussion of how this namelist could be changed.
