### ISSUE TITLE
Use explicit CX namelist for global surface observations

### ISSUE THREAD

**Issue by ldhawknesssmith** [MetOffice/opsinputs#155]
[opsinputs/pull/152](https://github.com/MetOffice/opsinputs/pull/152) introduces the CX namelist for global surface observations. @ctgh suggested that it would be clearer to explicitly list the CX fields requested rather than using the add/remove option.

This should be a straightforward change to address with no change to the result.

**Comment by ctgh** [comment]
Hi @ldhawknesssmith, @JoanneAWaller, @ReubenHill,

I think it might be good to modify the namelist as mentioned above. It will make it much easier to see what CX columns are actually used in the surface processing. For example, it will be clear that the surface columns differ from the screen ones.

Maybe we could discuss that in an upcoming meeting?
