### ISSUE TITLE
Use actual channel number for index

### ISSUE THREAD

**Issue by orlewis** [MetOffice/opsinputs#159]
For the geo radiances I have found that the arrays do not get assigned correctly. If the offset is used it pushes the data to be recorded from the correct location but does not take into account channels that are skipped. 
I will add making use of the actual channel number to fill that position in an array. 

For example 12 channels, 1-12. No data from 1-4, 8 and 12. If offset by 4 would get [NaN.NaN,NaN,NaN,5,6,7,8,9,10,NaN,NaN]. Need to get [NaN.NaN,NaN,NaN,5,6,7,NaN,9,10,11,NaN].

**Comment by ctgh** [comment]
@orlewis Can I check that this issue has been resolved by the accompanying PR?

**Comment by orlewis** [comment]
Yes that is correct, so I will close.

**Comment by ctgh** [comment]
Thanks!
