### ISSUE TITLE
SurfaceCloud CX field change

### ISSUE THREAD

**Issue by PJLevensMO** [MetOffice/opsinputs#179]
Currently the CX fields for SurfaceCloud contains field 1, which is called `pstar`, and was what is used in OPS. It looks like that field is going away, as it does not appear in the Field Names spreadsheet that's been put together by Steve S. I think we will need to replace this field with one (or two) of the others.

Most other instruments (those currently in the global) have one or both of fields 409 (`surface_air_pressure`) and 16222 (`air_pressure_at_mean_sea_level`) which I think we will need to replace field 1 with here. I don't really understand the difference between these two fields, or whether we will need both. Noticeably sondes only have field 409.

Can anyone advise on this?

The file in question that will need changed is here: 
etc/ukv/cx/SurfaceCloud.nl
https://github.com/MetOffice/opsinputs/blob/65e4e93c1377a6d8d80da6e34ed9e4f1a16b9c9d/etc/ukv/cx/SurfaceCloud.nl

**Comment by ctgh** [comment]
@PJLevensMO Can I check if this issue is still active?

**Comment by PJLevensMO** [comment]
Thanks Chris, I'd forgotten all about this one. I don't think it's relevant anymore, I'll close it.

**Comment by ctgh** [comment]
Thanks!
