### ISSUE TITLE
AOCC compile failure

### ISSUE THREAD

**Issue by DJDavies2** [MetOffice/opsinputs#201]
opsinputs compilation is failing for aocc (EXZ):

F90-S-0155-Could not resolve generic procedure ops_mpl_gatherv (/home/h01/david.davies/cylc-run/mo-bundle-412/share/mo-bundle/opsinputs/deps/ops/public/GenMod_Core/gen_message_report_sync.inc: 57)
F90-S-0155-Could not resolve generic procedure ops_mpl_gatherv (/home/h01/david.davies/cylc-run/mo-bundle-412/share/mo-bundle/opsinputs/deps/ops/public/GenMod_Core/gen_message_report_sync.inc: 84)
  0 inform,   0 warnings,   2 severes, 0 fatal for gen_message_report_sync
gmake[2]: *** [opsinputs/deps/ops/CMakeFiles/ops.dir/build.make:415: opsinputs/deps/ops/CMakeFiles/ops.dir/public/GenMod_Core/GenMod_Core.F90.o] Error 1

**Comment by ctgh** [comment]
Fixed by #203
