### ISSUE TITLE
Patch OPS files that need to be modified

### ISSUE THREAD

**Issue by wsmigaj** [MetOffice/opsinputs#27]
Recently two PRs (#21 and #26) made modifications to some OPS source files. The script copying OPS sources to this repository should be modified to patch these files to prevent these modifications from being lost if the OPS sources are ever updated.

**Comment by ctgh** [comment]
@mikecooke77 , @adammaycock I am going through old opsinputs issues and noticed this one.
Is it necessary to update the files in the linked PRs? As far as I can tell they are:
* deps/ops/public/OpsMod_EnvUtils/OpsMod_EnvUtils.F90
* deps/ops/code/OpsMod_Varobs/Ops_SetupVarobsLevDepC.inc

**Comment by adammaycock** [comment]
My view is that this isn't necessary now. I can't see a reason why we would need to update from OPS source again, I can understand a requirement for that when opsinputs was in its infancy but unless someone disagrees I think it's OK to let OPS and opsinputs go their own way.

**Comment by ctgh** [comment]
@adammaycock Thanks, that makes sense. I will close this issue.
